#ifndef V8READER_CORE_V8METADATALEGACY_H
#define V8READER_CORE_V8METADATALEGACY_H

// Legacy metadata model extraction (P1/P2 classes).
// This header intentionally re-exports existing src-based interfaces.

#include "BaseMetadataObject.h"
#include "MetadataObjectWithSections.h"
#include "MetadataObjectInformationRegister.h"

#include "Requisite.h"
#include "Comand.h"
#include "Moxel.h"
#include "Tabular.h"
#include "Form.h"

#include "Catalogs.h"
#include "Documents.h"
#include "Reports.h"
#include "DataProcessors.h"
#include "Journals.h"
#include "Tasks.h"
#include "BusinessProceses.h"
#include "ExchangePlans.h"
#include "ChartOfCalculationTypes.h"

#include "InformationRegisters.h"
#include "AccumulationRegisters.h"
#include "CalculationRegisters.h"
#include "AccountingRegisters.h"

#include "NodeTypes.h"
#include "Parse_tree.h"
#include "ModuleTextStorage.h"
#include "guids.h"

#include "Bots.h"
#include "ChartOfCharacteristicTypes.h"
#include "ChartOfAccounts.h"
#include "CommonCommands.h"
#include "CommonModules.h"
#include "CommonAttributes.h"
#include "CommandGroups.h"
#include "CommonForms.h"
#include "FunctionalOptions.h"
#include "FunctionalOptionsParameters.h"
#include "DefinedTypes.h"
#include "EventSubscriptions.h"
#include "CommonPictures.h"
#include "FilterCriteria.h"
#include "CommonTemplates.h"
#include "HTTPServices.h"
#include "ExternalDataSources.h"
#include "IntegrationServices.h"
#include "Interfaces.h"
#include "Langs.h"
#include "ScheduledJobs.h"
#include "Roles.h"
#include "Styles.h"
#include "StyleItems.h"
#include "SettingsStorages.h"
#include "SessionParameters.h"
#include "TConstants.h"
#include "Subsystem.h"
#include "WebSocketClients.h"
#include "WebServices.h"
#include "XDTOPackages.h"
#include "WSReferences.h"

#include "Enums.h"
#include "Numerators.h"
#include "Sequences.h"
#include "MetaObject.h"
#include "Property.h"
#include "CommonMetadataObject.h"
#include "MDObject.h"

#endif // V8READER_CORE_V8METADATALEGACY_H
