name: Build C++Builder Project (Self-hosted)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Êëþ÷åâîé ìîìåíò: óêàçûâàåì ìåòêè âàøåãî runner
    runs-on: [Windows, x64, Self-hosted]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Build Environment
      shell: cmd
      run: |
        echo "C++Builder environment set."
    - name: Build Project (Debug)
      shell: cmd
      run: |
        echo "Building the project..."
        call "C:/Program Files (x86)/Embarcadero/Studio/37.0/bin/rsvars.bat"
        set INCLUDE="C:/Program Files (x86)/Embarcadero/Studio/37.0/include/windows/rtl";%INCLUDE%
        cd /d "S:/work/CPP/BDS13/v8reader"
        msbuild v8reader.cbproj /p:Configuration=Debug /p:Platform=Win32 /m
        echo "Build finished."

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: v8reader
        path: S:/work/CPP/BDS13/v8reader/Win32/Debug/v8reader.exe
        # Îáû÷íî áèíàðíèê ñîçäàåòñÿ â ïîäïàïêå Win32/Release
